# Data cleaning

* Removal of full duplicate rows
* Removal of instances assigned to more categories at the same time
* Merge of perex and title columns into a new combined text column
* Remove the smallest categories
* Split data to train, validation and test splits with using a specific seed

### Module imports

In [1]:
import pandas as pd
from pathlib import Path
from sklearn.model_selection import train_test_split

A module that was compiled using NumPy 1.x cannot be run in
NumPy 2.4.6 as it may crash. To support both 1.x and 2.x
versions of NumPy, modules must be compiled with NumPy 2.0.
Some module may need to rebuild instead e.g. with 'pybind11>=2.12'.

If you are a user of the module, the easiest solution will be to
downgrade to 'numpy<2' or try to upgrade the affected module.
We expect that some modules will need time to support NumPy 2.

Traceback (most recent call last):  File "<frozen runpy>", line 198, in _run_module_as_main
  File "<frozen runpy>", line 88, in _run_code
  File "/opt/conda/lib/python3.11/site-packages/ipykernel_launcher.py", line 18, in <module>
    app.launch_new_instance()
  File "/opt/conda/lib/python3.11/site-packages/traitlets/config/application.py", line 1053, in launch_instance
    app.start()
  File "/opt/conda/lib/python3.11/site-packages/ipykernel/kernelapp.py", line 739, in start
    self.io_loop.start()
  File "/opt/conda/lib/python3.11/site-packages/tornado/platform/asyncio.py", line 195, in start
    self.asyncio_loop.run_forever()
  File "/opt/conda/lib/python3.11/asyncio/base_events.py", line 607, in run_forever
    self._run_once()
  File "/opt/conda/lib/python3.11/asyncio/base_events.py", line 1922, in _run_once
    handle._run()
  File "/opt/conda/lib/python3.11/asyncio/events.py", line 80, in _run
    self._context.run(self._callback, *self._args)
  File "/opt/conda/lib/python3.11/site-packages/ipykernel/kernelbase.py", line 519, in dispatch_queue
    await self.process_one()
  File "/opt/conda/lib/python3.11/site-packages/ipykernel/kernelbase.py", line 508, in process_one
    await dispatch(*args)
  File "/opt/conda/lib/python3.11/site-packages/ipykernel/kernelbase.py", line 400, in dispatch_shell
    await result
  File "/opt/conda/lib/python3.11/site-packages/ipykernel/ipkernel.py", line 368, in execute_request
    await super().execute_request(stream, ident, parent)
  File "/opt/conda/lib/python3.11/site-packages/ipykernel/kernelbase.py", line 767, in execute_request
    reply_content = await reply_content
  File "/opt/conda/lib/python3.11/site-packages/ipykernel/ipkernel.py", line 455, in do_execute
    res = shell.run_cell(
  File "/opt/conda/lib/python3.11/site-packages/ipykernel/zmqshell.py", line 577, in run_cell
    return super().run_cell(*args, **kwargs)
  File "/opt/conda/lib/python3.11/site-packages/IPython/core/interactiveshell.py", line 3024, in run_cell
    result = self._run_cell(
  File "/opt/conda/lib/python3.11/site-packages/IPython/core/interactiveshell.py", line 3079, in _run_cell
    result = runner(coro)
  File "/opt/conda/lib/python3.11/site-packages/IPython/core/async_helpers.py", line 129, in _pseudo_sync_runner
    coro.send(None)
  File "/opt/conda/lib/python3.11/site-packages/IPython/core/interactiveshell.py", line 3284, in run_cell_async
    has_raised = await self.run_ast_nodes(code_ast.body, cell_name,
  File "/opt/conda/lib/python3.11/site-packages/IPython/core/interactiveshell.py", line 3466, in run_ast_nodes
    if await self.run_code(code, result, async_=asy):
  File "/opt/conda/lib/python3.11/site-packages/IPython/core/interactiveshell.py", line 3526, in run_code
    exec(code_obj, self.user_global_ns, self.user_ns)
  File "/tmp/ipykernel_915/3782227491.py", line 1, in <module>
    import pandas as pd
  File "/opt/conda/lib/python3.11/site-packages/pandas/__init__.py", line 46, in <module>
    from pandas.core.api import (
  File "/opt/conda/lib/python3.11/site-packages/pandas/core/api.py", line 27, in <module>
    from pandas.core.arrays import Categorical
  File "/opt/conda/lib/python3.11/site-packages/pandas/core/arrays/__init__.py", line 1, in <module>
    from pandas.core.arrays.arrow import ArrowExtensionArray
  File "/opt/conda/lib/python3.11/site-packages/pandas/core/arrays/arrow/__init__.py", line 5, in <module>
    from pandas.core.arrays.arrow.array import ArrowExtensionArray
  File "/opt/conda/lib/python3.11/site-packages/pandas/core/arrays/arrow/array.py", line 65, in <module>
    from pandas.core import (
  File "/opt/conda/lib/python3.11/site-packages/pandas/core/ops/__init__.py", line 9, in <module>
    from pandas.core.ops.array_ops import (
  File "/opt/conda/lib/python3.11/site-packages/pandas/core/ops/array_ops.py", line 55, in <module>
    from pandas.core.computation import expressions
  File "/opt/conda/lib/python3.11/site-packages/pandas/core/computation/expressions.py", line 23, in <module>
    from pandas.core.computation.check import NUMEXPR_INSTALLED
  File "/opt/conda/lib/python3.11/site-packages/pandas/core/computation/check.py", line 5, in <module>
    ne = import_optional_dependency("numexpr", errors="warn")
  File "/opt/conda/lib/python3.11/site-packages/pandas/compat/_optional.py", line 158, in import_optional_dependency
    module = importlib.import_module(name)
  File "/opt/conda/lib/python3.11/importlib/__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "/opt/conda/lib/python3.11/site-packages/numexpr/__init__.py", line 24, in <module>
    from numexpr.interpreter import MAX_THREADS, use_vml, __BLOCK_SIZE1__

AttributeError: _ARRAY_API not found

A module that was compiled using NumPy 1.x cannot be run in
NumPy 2.4.6 as it may crash. To support both 1.x and 2.x
versions of NumPy, modules must be compiled with NumPy 2.0.
Some module may need to rebuild instead e.g. with 'pybind11>=2.12'.

If you are a user of the module, the easiest solution will be to
downgrade to 'numpy<2' or try to upgrade the affected module.
We expect that some modules will need time to support NumPy 2.

Traceback (most recent call last):  File "<frozen runpy>", line 198, in _run_module_as_main
  File "<frozen runpy>", line 88, in _run_code
  File "/opt/conda/lib/python3.11/site-packages/ipykernel_launcher.py", line 18, in <module>
    app.launch_new_instance()
  File "/opt/conda/lib/python3.11/site-packages/traitlets/config/application.py", line 1053, in launch_instance
    app.start()
  File "/opt/conda/lib/python3.11/site-packages/ipykernel/kernelapp.py", line 739, in start
    self.io_loop.start()
  File "/opt/conda/lib/python3.11/site-packages/tornado/platform/asyncio.py", line 195, in start
    self.asyncio_loop.run_forever()
  File "/opt/conda/lib/python3.11/asyncio/base_events.py", line 607, in run_forever
    self._run_once()
  File "/opt/conda/lib/python3.11/asyncio/base_events.py", line 1922, in _run_once
    handle._run()
  File "/opt/conda/lib/python3.11/asyncio/events.py", line 80, in _run
    self._context.run(self._callback, *self._args)
  File "/opt/conda/lib/python3.11/site-packages/ipykernel/kernelbase.py", line 519, in dispatch_queue
    await self.process_one()
  File "/opt/conda/lib/python3.11/site-packages/ipykernel/kernelbase.py", line 508, in process_one
    await dispatch(*args)
  File "/opt/conda/lib/python3.11/site-packages/ipykernel/kernelbase.py", line 400, in dispatch_shell
    await result
  File "/opt/conda/lib/python3.11/site-packages/ipykernel/ipkernel.py", line 368, in execute_request
    await super().execute_request(stream, ident, parent)
  File "/opt/conda/lib/python3.11/site-packages/ipykernel/kernelbase.py", line 767, in execute_request
    reply_content = await reply_content
  File "/opt/conda/lib/python3.11/site-packages/ipykernel/ipkernel.py", line 455, in do_execute
    res = shell.run_cell(
  File "/opt/conda/lib/python3.11/site-packages/ipykernel/zmqshell.py", line 577, in run_cell
    return super().run_cell(*args, **kwargs)
  File "/opt/conda/lib/python3.11/site-packages/IPython/core/interactiveshell.py", line 3024, in run_cell
    result = self._run_cell(
  File "/opt/conda/lib/python3.11/site-packages/IPython/core/interactiveshell.py", line 3079, in _run_cell
    result = runner(coro)
  File "/opt/conda/lib/python3.11/site-packages/IPython/core/async_helpers.py", line 129, in _pseudo_sync_runner
    coro.send(None)
  File "/opt/conda/lib/python3.11/site-packages/IPython/core/interactiveshell.py", line 3284, in run_cell_async
    has_raised = await self.run_ast_nodes(code_ast.body, cell_name,
  File "/opt/conda/lib/python3.11/site-packages/IPython/core/interactiveshell.py", line 3466, in run_ast_nodes
    if await self.run_code(code, result, async_=asy):
  File "/opt/conda/lib/python3.11/site-packages/IPython/core/interactiveshell.py", line 3526, in run_code
    exec(code_obj, self.user_global_ns, self.user_ns)
  File "/tmp/ipykernel_915/3782227491.py", line 1, in <module>
    import pandas as pd
  File "/opt/conda/lib/python3.11/site-packages/pandas/__init__.py", line 46, in <module>
    from pandas.core.api import (
  File "/opt/conda/lib/python3.11/site-packages/pandas/core/api.py", line 27, in <module>
    from pandas.core.arrays import Categorical
  File "/opt/conda/lib/python3.11/site-packages/pandas/core/arrays/__init__.py", line 1, in <module>
    from pandas.core.arrays.arrow import ArrowExtensionArray
  File "/opt/conda/lib/python3.11/site-packages/pandas/core/arrays/arrow/__init__.py", line 5, in <module>
    from pandas.core.arrays.arrow.array import ArrowExtensionArray
  File "/opt/conda/lib/python3.11/site-packages/pandas/core/arrays/arrow/array.py", line 79, in <module>
    from pandas.core.arrays.masked import BaseMaskedArray
  File "/opt/conda/lib/python3.11/site-packages/pandas/core/arrays/masked.py", line 56, in <module>
    from pandas.core import (
  File "/opt/conda/lib/python3.11/site-packages/pandas/core/nanops.py", line 54, in <module>
    bn = import_optional_dependency("bottleneck", errors="warn")
  File "/opt/conda/lib/python3.11/site-packages/pandas/compat/_optional.py", line 158, in import_optional_dependency
    module = importlib.import_module(name)
  File "/opt/conda/lib/python3.11/importlib/__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "/opt/conda/lib/python3.11/site-packages/bottleneck/__init__.py", line 7, in <module>
    from .move import (move_argmax, move_argmin, move_max, move_mean, move_median,

AttributeError: _ARRAY_API not found

In [2]:
from src.config import RAW_DATA_PATH, CLEAN_DATA_PATH
from src.config import SEED, VAL_SIZE, TEST_SIZE

In [3]:
df = pd.read_csv(RAW_DATA_PATH)

In [4]:
original_row_count = df.shape[0]
print(f"We have loaded {original_row_count} rows")

We have loaded 111218 rows

In [5]:
df.head()

,category,rss_title,rss_perex
0,biatlon,"Krčmář dojel v hromadném závodě devátý, díky s...",Závod s hromadným startem v německém Oberhofu ...
1,biatlon,Česká vlajka byla v Pokljuce vidět i ve štafet...,Galerie
2,biatlon,Živě: Stíhací závod biatlonistek v Ruhpoldingu,"15. 1., 14:45"
3,fotbal,Bakoš dostal herdu do nosu a v zápase plném ka...,Slovenský útočník Marek Bakoš zařídil Plzni gó...
4,fotbal,"My moc chtěli a Plzeň moc nechtěla, zní z Ďolí...",Český fotbal hledá viníka skandálu odloženého ...

### Drop duplicate rows

In [6]:
df.drop_duplicates(inplace=True)
no_duplicates_row_count = df.shape[0]
print(f"We have dropped {original_row_count - no_duplicates_row_count} rows")

We have dropped 7185 rows

### Drop conflicting rows

In [7]:
conflict = df.groupby(["rss_title", "rss_perex"])["category"].transform("nunique") > 1
df = df[~conflict]

In [8]:
print(f"We have dropped {no_duplicates_row_count - df.shape[0]} conflicting rows")

We have dropped 27 conflicting rows

### Drop instances associated with categories that have too few samples

In [9]:
MIN_CLASS_COUNT = 100

counts = df["category"].value_counts()
small = counts[counts < MIN_CLASS_COUNT].index

print(f"MIN_CLASS_COUNT = {MIN_CLASS_COUNT}")
print(f"The classes that are too small are {list(small)}")

MIN_CLASS_COUNT = 100
The classes that are too small are ['baseball', 'krasobrusleni', 'rychlobrusleni', 'dostihy', 'futsal', 'rugby', 'hokejbal']

In [10]:
before_small_drop = df.shape[0]
df = df[~df["category"].isin(small)].reset_index(drop=True)
print(f"We have dropped {before_small_drop - df.shape[0]} rows across {len(small)} class(es): {list(small)}")

We have dropped 347 rows across 7 class(es): ['baseball', 'krasobrusleni', 'rychlobrusleni', 'dostihy', 'futsal', 'rugby', 'hokejbal']

### Build the text column

In [11]:
df["text"] = df["rss_title"].fillna("") + " " + df["rss_perex"].fillna("")
df = df.reset_index(drop=True)
df.head(3)

,category,rss_title,rss_perex,text
0,biatlon,"Krčmář dojel v hromadném závodě devátý, díky s...",Závod s hromadným startem v německém Oberhofu ...,"Krčmář dojel v hromadném závodě devátý, díky s..."
1,biatlon,Česká vlajka byla v Pokljuce vidět i ve štafet...,Galerie,Česká vlajka byla v Pokljuce vidět i ve štafet...
2,biatlon,Živě: Stíhací závod biatlonistek v Ruhpoldingu,"15. 1., 14:45",Živě: Stíhací závod biatlonistek v Ruhpoldingu...

# Split to train, val and test splits

Split to train + val AND test (combined)

In [12]:
val_test_size = VAL_SIZE + TEST_SIZE                
train_idx, val_test_idx = train_test_split(
    df.index, test_size=val_test_size, stratify=df["category"], random_state=SEED,
)

Split val AND test set to validation and testing sets that are separate

In [13]:
test_frac = TEST_SIZE / val_test_size           
val_idx, test_idx = train_test_split(
    val_test_idx, test_size=test_frac, stratify=df.loc[val_test_idx, "category"], random_state=SEED,
)

Assign to appropriate columns

In [14]:
df["split"] = "train"
df.loc[val_idx, "split"] = "val"
df.loc[test_idx, "split"] = "test"

In [15]:
print(df["split"].value_counts(normalize=True).round(3))

split
train    0.8
val      0.1
test     0.1
Name: proportion, dtype: float64

In [16]:
distribution = (
    df.groupby("split")["category"]
    .value_counts(normalize=True)
    .unstack(level=0)
    .mul(100)
    .round(2)
)
display(distribution.sort_values("train", ascending=False))

split            test  train    val
category
fotbal          41.15  41.15  41.14
hokej           25.90  25.90  25.90
tenis           10.49  10.48  10.48
formule1         5.44   5.44   5.44
moto             4.50   4.50   4.50
atletika         2.23   2.22   2.22
basketbal        2.21   2.22   2.22
cyklistika       1.79   1.79   1.79
biatlon          1.42   1.42   1.42
olympijske_hry   1.17   1.17   1.17
lyze_snowboard   0.87   0.87   0.87
volejbal         0.75   0.76   0.76
hazena           0.61   0.61   0.62
florbal          0.47   0.48   0.47
vodni_sporty     0.48   0.48   0.48
golf             0.41   0.41   0.41
box              0.12   0.11   0.12

### Export to intermediary file

In [17]:
df.to_parquet(CLEAN_DATA_PATH)
print(f"Saved: {CLEAN_DATA_PATH}  ({len(df)} rows)")

Saved: /home/jovyan/sport_article_classifier/data/clean.parquet  (103659 rows)