# Data cleaning

* Removal of full duplicit rows
* Removal of instances assigned to more categories at the same time
* Merge of perex and title columns into a new combined text column

### Module imports

In [1]:
import pandas as pd
from pathlib import Path

In [2]:
data_path = Path("../data/sportoclanky.csv.gz")
df = pd.read_csv(data_path)

In [3]:
original_row_count = df.shape[0]
print(f"We have loaded {original_row_count} rows")

We have loaded 111218 rows

In [4]:
df.head()

,category,rss_title,rss_perex
0,biatlon,"Krčmář dojel v hromadném závodě devátý, díky s...",Závod s hromadným startem v německém Oberhofu ...
1,biatlon,Česká vlajka byla v Pokljuce vidět i ve štafet...,Galerie
2,biatlon,Živě: Stíhací závod biatlonistek v Ruhpoldingu,"15. 1., 14:45"
3,fotbal,Bakoš dostal herdu do nosu a v zápase plném ka...,Slovenský útočník Marek Bakoš zařídil Plzni gó...
4,fotbal,"My moc chtěli a Plzeň moc nechtěla, zní z Ďolí...",Český fotbal hledá viníka skandálu odloženého ...

### Drop duplicate rows

In [5]:
df.drop_duplicates(inplace=True)
no_duplicates_row_count = df.shape[0]
print(f"We have dropped {original_row_count - no_duplicates_row_count} rows")

We have dropped 7185 rows

### Drop conflicting rows

In [6]:
conflict = df.groupby(["rss_title", "rss_perex"])["category"].transform("nunique") > 1
df = df[~conflict]

In [7]:
print(f"We have dropped {no_duplicates_row_count - df.shape[0]} conflicting rows")

We have dropped 27 conflicting rows

### Build the text column

In [8]:
df["text"] = df["rss_title"] + " " + df["rss_perex"]
df = df.reset_index(drop=True)
df.head(3)

,category,rss_title,rss_perex,text
0,biatlon,"Krčmář dojel v hromadném závodě devátý, díky s...",Závod s hromadným startem v německém Oberhofu ...,"Krčmář dojel v hromadném závodě devátý, díky s..."
1,biatlon,Česká vlajka byla v Pokljuce vidět i ve štafet...,Galerie,Česká vlajka byla v Pokljuce vidět i ve štafet...
2,biatlon,Živě: Stíhací závod biatlonistek v Ruhpoldingu,"15. 1., 14:45",Živě: Stíhací závod biatlonistek v Ruhpoldingu...

### Export to intermediary file

In [9]:
data_out_path = Path("../data/clean_data.parquet")
df.to_parquet(data_out_path)
print(f"Saved: {data_out_path}  ({len(df)} rows)")

Saved: ../data/clean_data.parquet  (104006 rows)